In [3]:
from dateutil import parser

In [4]:
date = '2023-04-11 07:34:58'

print(type(date))

<class 'str'>

In [5]:
date = parser.parse(date)

In [6]:
print((date))

2023-04-11 07:34:58

In [7]:
date.year

2023

In [8]:
date.day

11

In [9]:
date.month

4

In [10]:
date.weekday()

1

In [11]:
date.hour

7

In [12]:
date.minute

34

In [13]:
date.second

58

In [14]:
date2 = '2023-04-10 19:13:36'

date2 = parser.parse(date2)

In [15]:
date2.hour

19

In [16]:
def extract_date(date):
    date = parser.parse(date)
    return (date.year, date.month, date.day, date.weekday(), date.hour, date.minute, date.second)

In [17]:
extract_date('2023-04-10 19:13:36')

(2023, 4, 10, 0, 19, 13, 36)

In [18]:
import pandas as pd
import numpy as np
import mysql.connector

In [19]:
db = mysql.connector.connect(
    host = 'localhost',
    user = 'root',
    password='root'

)

mycursor = db.cursor()

In [20]:
querry = 'SELECT * FROM mtracker.transaction_type;'

df = pd.read_sql(querry, db, parse_dates = True)

C:\Users\Administrator\anaconda3\lib\site-packages\pandas\io\sql.py:761: UserWarning: pandas only support SQLAlchemy connectable(engine/connection) ordatabase string URI or sqlite3 DBAPI2 connectionother DBAPI2 objects are not tested, please consider using SQLAlchemy
  warnings.warn(

In [21]:
df

,Receipt No.,Completion Time,Details,Transaction Status,Paid In,Withdrawn,Balance,transaction_type
0,RDB7VLX827,2023-04-11 07:34:58,Merchant Payment to 7603071 - EUNICE RURII,Completed,None,-10,190.65,TILL PAYMENT
1,RDB0VIRHTI,2023-04-11 06:17:55,Pay Bill Online to 888880 - KPLC PREPAID Acc. ...,Completed,None,-20,200.65,PAY BILL
2,RDA8V2XOWG,2023-04-10 20:28:58,Customer Transfer to - 07******179 Peter Osodo,Completed,None,-20,220.65,SEND MONEY
3,RDA4V2RODM,2023-04-10 20:27:28,Merchant Payment to 7569854 - SAMUEL NDUNGU,Completed,None,-20,240.65,TILL PAYMENT
4,RDA1V266WT,2023-04-10 20:22:35,Merchant Payment to 7441768 - JAWS BUTCHERY,Completed,None,-100,260.65,TILL PAYMENT
...,...,...,...,...,...,...,...,...
1131,RA10GI49RQ,2023-01-01 10:02:33,Pay Bill Charge,Completed,None,-4,0,PAY BILL CHARGES
1132,RA10GI49RQ,2023-01-01 10:02:33,OverDraft of Credit Party,Completed,454,None,4,FULIZA TAKEN
1133,RA10GI49RQ,2023-01-01 10:02:33,Pay Bill Online Fuliza M-Pesa to 247247 - Equi...,Completed,None,-450,-450,PAY BILL
1134,RA10GI2APY,2023-01-01 10:01:48,OD Loan Repayment to 232323 - M-PESA Overdraw,Completed,None,-50,0,FULIZA REPAYMENT
1135,RA12GI1SRW,2023-01-01 10:01:48,KCB M-PESA Withdraw,Completed,50,None,50,KCB MPESA WITHDRAW TO MPESA

In [22]:
dates = df['Completion Time'].apply(lambda x: extract_date(x)).values

In [23]:
year = [i[0] for i in dates]
month = [i[1] for i in dates]
date = [i[2] for i in dates]
weekday = [i[3] for i in dates]
hour = [i[4] for i in dates]
minute = [i[5] for i in dates]
second = [i[6] for i in dates]

In [32]:
date
trasaction_day = []
datex = date[0]
d = 1

for i in date:
    if i == datex:
        trasaction_day.append(d)
    else:
        datex = i
        d+= 1
        trasaction_day.append(d)

1136

97

In [25]:
df.insert(2, 'year', year)
df.insert(3, 'month', month)
df.insert(4, 'date', date)
df.insert(5, 'weekday', weekday)
df.insert(6, 'hour', hour)
df.insert(7, 'minute', minute)
df.insert(8, 'second', second)

In [26]:
df.head(40)

,Receipt No.,Completion Time,year,month,date,weekday,hour,minute,second,Details,Transaction Status,Paid In,Withdrawn,Balance,transaction_type
0,RDB7VLX827,2023-04-11 07:34:58,2023,4,11,1,7,34,58,Merchant Payment to 7603071 - EUNICE RURII,Completed,None,-10,190.65,TILL PAYMENT
1,RDB0VIRHTI,2023-04-11 06:17:55,2023,4,11,1,6,17,55,Pay Bill Online to 888880 - KPLC PREPAID Acc. ...,Completed,None,-20,200.65,PAY BILL
2,RDA8V2XOWG,2023-04-10 20:28:58,2023,4,10,0,20,28,58,Customer Transfer to - 07******179 Peter Osodo,Completed,None,-20,220.65,SEND MONEY
3,RDA4V2RODM,2023-04-10 20:27:28,2023,4,10,0,20,27,28,Merchant Payment to 7569854 - SAMUEL NDUNGU,Completed,None,-20,240.65,TILL PAYMENT
4,RDA1V266WT,2023-04-10 20:22:35,2023,4,10,0,20,22,35,Merchant Payment to 7441768 - JAWS BUTCHERY,Completed,None,-100,260.65,TILL PAYMENT
5,RDA3V11ZWX,2023-04-10 20:13:36,2023,4,10,0,20,13,36,Customer Transfer to - 2547******334 RISPA AMA...,Completed,None,-10,360.65,SEND MONEY
6,RDA4V0W7G8,2023-04-10 20:12:19,2023,4,10,0,20,12,19,Customer Transfer to - 2547******184 JACINTA N...,Completed,None,-15,370.65,SEND MONEY
7,RDA1V0LT5P,2023-04-10 20:10:06,2023,4,10,0,20,10,6,Customer Payment to Small Business to - 2547**...,Completed,None,-15,385.65,POCHI LA BIASHARA
8,RDA0V0824U,2023-04-10 20:07:17,2023,4,10,0,20,7,17,Merchant Payment to 7139380 - JACKSON MWAURA M...,Completed,None,-20,400.65,TILL PAYMENT
9,RDA9UZI3MB,2023-04-10 20:01:50,2023,4,10,0,20,1,50,Customer Payment to Small Business to - 2547**...,Completed,None,-10,420.65,POCHI LA BIASHARA
10,RDA6UW2UUC,2023-04-10 19:37:35,2023,4,10,0,19,37,35,Merchant Payment to 7421237 - MARY ELIZABETH W...,Completed,None,-20,430.65,TILL PAYMENT
11,RDA3USE1PP,2023-04-10 19:13:36,2023,4,10,0,19,13,36,Withdrawal Charge,Completed,None,-28,450.65,CASH WITHDRAWAL CHARGES
12,RDA3USE1PP,2023-04-10 19:13:36,2023,4,10,0,19,13,36,Customer Withdrawal At Agent Till 087443 - Dot...,Completed,None,-851,478.65,CASH WITHDRAWAL
13,RDA8U2U0DI,2023-04-10 15:22:14,2023,4,10,0,15,22,14,Merchant Payment Online to 7603071 - EUNICE RURII,Completed,None,-70,"1,329.65",TILL PAYMENT
14,RDA9TQVC6F,2023-04-10 13:12:07,2023,4,10,0,13,12,7,Funds received from - 2547******095 MERCY MULWA,Completed,"1,000.00",None,"1,399.65",RECEIVE FUNDS FROM PERSON
15,RDA3T1S1T5,2023-04-10 08:12:00,2023,4,10,0,8,12,0,Funds received from - 07******759 alfred karas...,Completed,200.00,None,399.65,RECEIVE FUNDS FROM PERSON
16,RDA9SXNVQD,2023-04-10 06:43:34,2023,4,10,0,6,43,34,Funds received from - 2547******403 Peter Kiania,Completed,150.00,None,204.00,RECEIVE FUNDS FROM PERSON
17,RDA5SXNX8P,2023-04-10 06:43:34,2023,4,10,0,6,43,34,OD Loan Repayment to 232323 - M-PESA Overdraw,Completed,None,-4.35,199.65,FULIZA REPAYMENT
18,RDA6SU0Z30,2023-04-10 00:00:25,2023,4,10,0,0,0,25,Pay Bill Online to 888880 - KPLC PREPAID Acc. ...,Completed,None,-50,54.00,PAY BILL
19,RDA8SU0CEO,2023-04-10 00:00:08,2023,4,10,0,0,0,8,Airtime Purchase,Completed,None,-30,104.00,AIRTIME PURCHASE
20,RD91SQHOXN,2023-04-09 22:15:51,2023,4,9,6,22,15,51,Customer Transfer of Funds Charge,Completed,None,-6,134.00,SEND MONEY
21,RD91SQHOXN,2023-04-09 22:15:51,2023,4,9,6,22,15,51,Customer Transfer to - 2547******705 SIMON WAC...,Completed,None,-500.00,140.00,SEND MONEY
22,RD95SMKZQ9,2023-04-09 21:20:26,2023,4,9,6,21,20,26,Airtime Purchase,Completed,None,-20.00,640.00,AIRTIME PURCHASE
23,RD90RVIEW8,2023-04-09 17:23:38,2023,4,9,6,17,23,38,Customer Transfer to - 07******723 ESAU KURUSWO,Completed,None,-10.00,660.00,SEND MONEY
24,RD93RUFKQF,2023-04-09 17:12:57,2023,4,9,6,17,12,57,Merchant Payment to 7134537 - HANAH WANJA MUYA 06,Completed,None,-30.00,670.00,TILL PAYMENT
25,RD99R14DYZ,2023-04-09 11:44:00,2023,4,9,6,11,44,0,Pay Bill Online to 888880 - KPLC PREPAID Acc. ...,Completed,None,-20.00,700.00,PAY BILL
26,RD92QYO5QM,2023-04-09 11:11:32,2023,4,9,6,11,11,32,Merchant Payment to 829247 - DOUGLAS MUTUMA SHOP1,Completed,None,-100.00,720.00,TILL PAYMENT
27,RD81PYAMKZ,2023-04-08 20:13:05,2023,4,8,5,20,13,5,Merchant Payment Online to 7039091 - OMUNDO SU...,Completed,None,-25.00,820.00,TILL PAYMENT
28,RD89PY50IR,2023-04-08 20:11:50,2023,4,8,5,20,11,50,Merchant Payment Online to 7603071 - EUNICE RURII,Completed,None,-5.00,845.00,TILL PAYMENT
29,RD83PXTI4T,2023-04-08 20:09:17,2023,4,8,5,20,9,17,Merchant Payment Online to 953827 - IRENE NGEN...,Completed,None,-5.00,850.00,TILL PAYMENT
30,RD85PWR6MX,2023-04-08 20:01:10,2023,4,8,5,20,1,10,Merchant Payment to 7013655 - STANELY NJUGUNA ...,Completed,None,-130.00,855.00,TILL PAYMENT
31,RD85PWMDVR,2023-04-08 20:00:09,2023,4,8,5,20,0,9,Airtime Purchase,Completed,None,-10.00,985.00,AIRTIME PURCHASE
32,RD88OSVMBC,2023-04-08 14:19:53,2023,4,8,5,14,19,53,Merchant Payment Online to 7603071 - EUNICE RURII,Completed,None,-5.00,995.00,TILL PAYMENT
33,RD86ORXO5S,2023-04-08 14:10:38,2023,4,8,5,14,10,38,Merchant Payment Online to 7603071 - EUNICE RURII,Completed,None,-110.00,"1,000.00",TILL PAYMENT
34,RD86NMQ3J8,2023-04-08 00:06:03,2023,4,8,5,0,6,3,Buy Bundles Online,Completed,None,-30.00,"1,110.00",BUNDLES PURCHASE
35,RD72NA0AEU,2023-04-07 20:43:35,2023,4,7,4,20,43,35,Savings Contribution,Completed,None,-60.00,"1,140.00",TO HUSTLER FUND SAVINGS
36,RD72NA0AEU,2023-04-07 20:43:35,2023,4,7,4,20,43,35,Term Loan Disbursement for H- Fund,Completed,"1,200.00",None,"1,200.00",HUSTLER FUND DISBURSEMENT
37,RD75N75T65,2023-04-07 20:20:27,2023,4,7,4,20,20,27,Pay Bill Charge,Completed,None,-19.00,0.00,PAY BILL CHARGES
38,RD75N75T65,2023-04-07 20:20:27,2023,4,7,4,20,20,27,OverDraft of Credit Party,Completed,4.30,None,19.00,FULIZA TAKEN
39,RD75N75T65,2023-04-07 20:20:27,2023,4,7,4,20,20,27,Pay Bill Online Fuliza M-Pesa to 4018913 - FLU...,Completed,None,"-2,000.00",14.70,PAY BILL

In [27]:
#######################################################

In [28]:
x = 'Customer Withdrawal At Agent Till 087443 - Dotnet Systems Amkar Shop Juja Agg'
index = x.find(' - ')+3
name =  x[index:].strip().upper()
    
name

'DOTNET SYSTEMS AMKAR SHOP JUJA AGG'

In [29]:
df

,Receipt No.,Completion Time,year,month,date,weekday,hour,minute,second,Details,Transaction Status,Paid In,Withdrawn,Balance,transaction_type
0,RDB7VLX827,2023-04-11 07:34:58,2023,4,11,1,7,34,58,Merchant Payment to 7603071 - EUNICE RURII,Completed,None,-10,190.65,TILL PAYMENT
1,RDB0VIRHTI,2023-04-11 06:17:55,2023,4,11,1,6,17,55,Pay Bill Online to 888880 - KPLC PREPAID Acc. ...,Completed,None,-20,200.65,PAY BILL
2,RDA8V2XOWG,2023-04-10 20:28:58,2023,4,10,0,20,28,58,Customer Transfer to - 07******179 Peter Osodo,Completed,None,-20,220.65,SEND MONEY
3,RDA4V2RODM,2023-04-10 20:27:28,2023,4,10,0,20,27,28,Merchant Payment to 7569854 - SAMUEL NDUNGU,Completed,None,-20,240.65,TILL PAYMENT
4,RDA1V266WT,2023-04-10 20:22:35,2023,4,10,0,20,22,35,Merchant Payment to 7441768 - JAWS BUTCHERY,Completed,None,-100,260.65,TILL PAYMENT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1131,RA10GI49RQ,2023-01-01 10:02:33,2023,1,1,6,10,2,33,Pay Bill Charge,Completed,None,-4,0,PAY BILL CHARGES
1132,RA10GI49RQ,2023-01-01 10:02:33,2023,1,1,6,10,2,33,OverDraft of Credit Party,Completed,454,None,4,FULIZA TAKEN
1133,RA10GI49RQ,2023-01-01 10:02:33,2023,1,1,6,10,2,33,Pay Bill Online Fuliza M-Pesa to 247247 - Equi...,Completed,None,-450,-450,PAY BILL
1134,RA10GI2APY,2023-01-01 10:01:48,2023,1,1,6,10,1,48,OD Loan Repayment to 232323 - M-PESA Overdraw,Completed,None,-50,0,FULIZA REPAYMENT
1135,RA12GI1SRW,2023-01-01 10:01:48,2023,1,1,6,10,1,48,KCB M-PESA Withdraw,Completed,50,None,50,KCB MPESA WITHDRAW TO MPESA

In [1]:
my_list = [1, 2, 3, 4, 5]
my_list.reverse()
print(my_list)

[5, 4, 3, 2, 1]